#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=99
STOP=8

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh "/usr/sbin/hopbox-httping"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/hopbox-httping.pid
	procd_close_instance
}

stop_service() {
	PID=`cat /var/run/hopbox-httping.pid`
	if [ -n "${PID}" ]
	then
		list_descendants () {
	
			local children=$(ps -o pid= --ppid "$1")

			for pid in $children
			do
				list_descendants ${pid}
			done
        		echo "$children"
		}

       		kill $(list_descendants ${PID})
       fi
}
